### ISSUE TITLE
Error using "once" inside a function on an Eloquent model 

### ISSUE THREAD

**Issue by lukeramsden** [spatie/once#26]
Appears that if I use "once" inside a member function for one of my Eloquent models, it breaks when trying to save the model:

```
class User extends Model
{
    public function hasCreatedAddress()
    {
        return once(function ()
        {
            return $this->isValidCompany() && $this->userable->company->addresses()->count() > 0;
        });
    }
}
```

When I save the model, it throws an error:
 `Object of class Spatie\Once\Listener could not be converted to string`. 
As far as I can tell this is because it's attempting to save the `___once_listener__xxx` properties that  `Spatie\Once\Cache` adds? I'm not too sure, but it seems obvious to me that it's the library causing the issue. Just posting this here in case someone has a real workaround, because for now I'm just going to have to remove the library and use static function variables instead:

```
    public function hasCreatedAddress()
    {
        static $b = null;

        if(is_null($b))
            $b = $this->isValidCompany() && $this->userable->company->addresses()->count() > 0;

        return $b;
    }
```

Image of the error: 
![screenshot from 2018-07-03 14-08-00](https://user-images.githubusercontent.com/13789719/42221622-96867fda-7eca-11e8-80e4-fd49277540ac.png)

**Comment by pascalbaljet** [comment]
It sets the listener as an attribute on the model (instead of a property). When you try to update the model it fails because it can't save the listener to the DB :)

**Comment by zanemmm** [comment]
try this
``` PHP
class User extends Model
{
    public function hasCreatedAddress()
    {
        $do = function () {
            return $this->isValidCompany() && $this->userable->company->addresses()->count() > 0;
        };
        return once($do->bindTo($this, $this));
    }
}
```

I think it would help you, about [Closure::bindTo](http://php.net/manual/en/closure.bindto.php) :smiley:

**Comment by ragingdave** [comment]
This is still an issue and the bindTo doesn't resolve it. Anyway you slice it, this in combination with Eloquent Models, will be an issue because the default __set method will always set the property as a model attribute. __memoized worked because you could just use the base model and add the property, which bypassed the setAttribute logic. At this time it seems that v2 of this package is incompatible with laravel models.

**Comment by tutNichts** [comment]
@ragingdave same here

**Comment by JayBizzle** [comment]
Any way to address this? Most of my use cases for this function are on Eloquent Models 😟

**Comment by ragingdave** [comment]
@JayBizzle use v1...?

**Comment by JayBizzle** [comment]
> @JayBizzle use v1...?

Oh, really, totally missed that that was an option. Will give it a try, thanks!

**Comment by kitbs** [comment]
I am using v1.1.0 because that's what Nova still requires, and this same issue still exists, but for a different reason.

You can get around the issue in v1.* if you add `public $__memoized;` to your model. (I don't know if this is a great, permanent fix, but it certainly helped as a workaround.)

The `MemoizeAwareTrait` trait has the variable as **protected** but because the only place it's accessed is from _outside_ the class, that variable will never be accessible. That's why it's falling back to the `__get()`/`__set()`, which is getting tangled in Eloquent's attribute methods.

From v2.0.0 up, the way of storing the cached values is completely different, so this is not relevant. Sorry I don't have an answer to the original issue.

**Comment by gerardnll** [comment]
Is there any reason why this is closed? It's happening to me with version 2.
Can we expect a fix? Or it is something we shouldn't use in eloquent models? Maybe I haven't understood the point of this package.

**Comment by riesjart** [comment]
A workaround for v2 appears to be adding the following to your (base) model (trait):

```php
protected $onceListeners = [];

public function __get($key)
{
    if (Str::startsWith($key, '___once_listener__')) {

        return $this->onceListeners[$key];
    }

    return parent::__get($key);
}

public function __set($key, $value)
{
    if (Str::startsWith($key, '___once_listener__')) {

        $this->onceListeners[$key] = $value;

        return;
    }

    parent::__set($key, $value);
}
```

**Comment by ragingdave** [comment]
That solution for a small project would be fine but the amountof overhead to call startsWith on literally every property access is too high in my book

**Comment by devfrey** [comment]
I wonder why this issue was closed – I'm experiencing the same problem.

**Comment by ragingdave** [comment]
I'm not sure how or why but it seems that in the latest version of both Laravel and this package (2.2)...usage of once in models is somehow working? Not sure how/why it started working but will definitely be doing more testing in my other apps to confirm

**Comment by gerardnll** [comment]
Yes... the other day I reimplemented what it was once (pun) breaking and I see no issues now... don’t know what changed.

**Comment by reganjohnson** [comment]
On Laravel 7, having this issue when trying to pass values into a model update statement that were returned from a chain of once();

**Comment by ragingdave** [comment]
@reganjohnson I would think that there must be something else going on as a value from once or not doesn't really matter since it will resolve to the value, not some wrapped object. I would also point out as well about the potential performance hit to have a check like that on literally every property...

Can you elaborate on the error you are getting? or is it the exact same error originally reported?

**Comment by riesjart** [comment]
This no longer appears to be an issue in v3, which doesn't use the `___once_listener__`.

**Comment by stevebauman** [comment]
Dang, ran into this myself today. Can't use this package atm while we port to PHP 8. 😢
